#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u 'umarhafeez27' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"


#test if you are  running from direcutory
#git init
#git remote add origin "https://github.com/umarhafeez27/$repo_name.git"
